palzo/sansaninfo

- app/src/main/java/com/example/sansaninfo/Fragment/SignInFragment.kt
- app/src/main/java/com/example/sansaninfo/Fragment/SignUpFragment.kt
- app/src/main/res/layout/fragment_sign_in.xml
- app/src/main/res/layout/fragment_sign_up.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
파이어베이스 로그인 및 회원가입 기능 연결을 위한 signin & signup fragment의 간단한 ui 틀 구현완료
- [DESIGN] : 🎨 로그인 & 회원가입 페이지 ui 구현
- [DESIGN] : 🎨 color에 컬러 코드 데이터 추가
close #2
> [DESIGN] : 🎨 로그인 & 회원가입 페이지 ui 틀 구현

- app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
- app/src/main/res/layout/activity_info_page.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/weather_item.xml
- app/src/main/res/values/strings.xml
mypage, infopage xml 파일 업데이트
close #11
> [DESIGN] : 🎨: mypage, infopage

- app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
- app/src/main/res/layout/fragment_my_page.xml
> [Feature] 회원탈퇴, 로그아웃

- .idea/misc.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
- app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiService.kt
- app/src/main/java/com/example/sansaninfo/SearchPage/MountainMapping.kt
- app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
- app/src/main/res/drawable/powerspinner_bar.xml
- app/src/main/res/layout/fragment_search_page_mountain.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
1. 지역명으로 검색 스피너 아이템 클릭시 해당하는 지역의 산을 출력
2. HashMap<산 이름, 산 코드> 작성하는 파일 생성
close #38
> [FEAT] : ⚙️: 지역명으로 검색 기능 추가

- app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/res/layout/activity_detail_page.xml
AddPageActivity 수정
activity_detail_page.xml 수정
> [FIX] : 🐛: 잔잔바리 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/sansaninfo/GlobalApplication.kt
- app/src/main/res/drawable/signin_btn_kakao.xml
- app/src/main/res/layout/activity_info_page.xml
> [FEAT] : 1. GlobalApplication.kt 파일 추가

- app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
- app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/res/drawable/alert_triangle.xml
> [FEAT] : ⚙️ 삭제하기

- .idea/misc.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/sansaninfo/Chatting/ChattingListAdapter.kt
- app/src/main/java/com/example/sansaninfo/Chatting/ChattingListFragment.kt
- app/src/main/java/com/example/sansaninfo/Chatting/ChattingModel.kt
- app/src/main/java/com/example/sansaninfo/Chatting/ChattingPage.kt
- app/src/main/java/com/example/sansaninfo/Main/MainViewPagerAdapter.kt
- app/src/main/res/drawable/ic_chat.xml
- app/src/main/res/layout/activity_chatting_page.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/chatting_list_item.xml
- app/src/main/res/layout/fragment_chatting_list.xml
- app/src/main/res/menu/tabs.xml
- app/src/main/res/values/strings.xml
1. chatting page 화면 추가
2. chatting list fragment 화면 추가
> [UI] : 채팅 화면 추가

- app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
- app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
- app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/java/com/example/sansaninfo/Main/MainActivity.kt
- app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
- app/src/main/res/layout/activity_main.xml
1. 게시글을 올리고 작성자 화면을 제공합니다.
close #102
> [FEAT] : AddPage -> DetailPage

- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/activity_sign_up.xml
> [Design]: 회원가입 페이지 제목과 자동로그인,이메일 저장 스타일 적용

- app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
> [FEAT] : 1. 수정하기

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/Chatting/MsgListAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/Data/PostModel.kt
- app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
- app/src/main/res/drawable/add_page_stroke_round_rec_err.xml
- app/src/main/res/layout/activity_add_page.xml
- app/src/main/res/layout/activity_detail_page.xml
- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/community_page_item.xml
- app/src/main/res/layout/fragment_community_page.xml
> [feature] : 1. community, add, detail page

- app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/Data/RoomData.kt
- app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
> [FIX] : 🐛 채팅 목록 오류 잡기

- app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
- app/src/main/res/layout/fragment_chatting_list.xml
- 채팅 목록에 자신이 참여한 채팅방 목록만 보여주기
- 채팅하기 버튼 기능 삭제하기
close #140
> [Chatting Page] 채팅 목록 구현하기

- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
- 로그인된 유저와 이외의 유저가 채팅할 때의 viewType이 나뉘었을 때 깜빡거림 문제 해결     
- MsgListAdapter.kt
- ChatRoomActivity.kt
close #147
> [Chatting-page] viewType 작업수정완료 

- app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/BaseActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/InfoPage/InfoPage.kt
- app/src/main/java/com/sandamso/sansaninfo/MyPage/ChangeNicknameActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/MyPage/MyPageFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/SignPage/FindpwActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/SignPage/SignUpActivity.kt
- app/src/main/res/drawable/background_toast.xml
- app/src/main/res/drawable/ic_logo_msg.xml
- app/src/main/res/layout/toast_msg.xml
- Toast Message 디자인 변경해서 각 페이지 별로 수정 완료했습니다.
> [Toast Message] 디자인 변경

- app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
> [Dday] CommunityPage, DetailPage

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
> 채팅 알람 기능 구현

- app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/Main/MainActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/Main/MainTab.kt
- app/src/main/java/com/sandamso/sansaninfo/Main/MainViewPagerAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/SearchPage/SearchPageMountainFragment.kt
- spinner 선택 후 tab바 이용해서 다른 fragment로 넘어갈 때 spinner 목록이 다른 UI 상에 밀리면서 노출되는 부분 해결
- spinner 선택 후 spinner 이외의 다른 부분 선택 시 자동으로 닫히도록 구현
- CommunityPageFragment.kt
- SearchPageFragment.kt
- MainActivity.kt
- MainTab.kt
- MainViewPageAdapter.kt
close #159
> [Community, Search-page] 스피너 기능 수정완료

- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/list_talk_item_mine.xml
- app/src/main/res/layout/list_talk_item_others.xml
- 오전/오후 표시
- '시간'과 '분' 표시
- 말풍선 디자인 수정
close #156
> [ChattingPage] 채팅 말풍선 수정

- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomListAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
- 아이템 길게 클릭했을 때, <채팅방 나가기> Dialog 보여주기
- "확인" 클릭 시 채팅방 삭제하기
- Firebase Realtime DB에서 채팅방을 나간 user 정보 삭제하기
- 채팅방을 나가는 과정에서 채팅방에 다른 유저가 없으면 채팅방 정보 삭제하기
close #166
> [FEAT] : ⚙️ 채팅방 나가기 기능 구현

- app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
- app/src/main/res/layout/activity_add_page.xml
- Add Page에서 Detail Page로 넘어갈 때 프로그래스 바만 보이게 하기
- Add Page xml 파일에서 Group & AddPageActivity 수정 - 버튼 안보이게 하기
> [LITTLE_FIX] : 🔧 로딩 중 프로그래스 바만 보이게 구현하기

- app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
- app/src/main/res/layout/activity_info_page.xml
- 마감일이 지난 게시글에는 참여하기 기능 버튼이 안보이도록 수정 완료
- 검색 페이지 - **모임만들기** 버튼 위치 조정하기
close #174 
- DetailPageActivity.kt
- activity_info_page.xml
> 참여하기 버튼 비활성화

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/mypage/MyPageFragment.kt
- app/src/main/res/layout/activity_findpw.xml
- app/src/main/res/layout/activity_findpw_result.xml
- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/activity_sign_up.xml
- app/src/main/res/layout/community_page_item.xml
> [FEAT] : ⚙️: 커뮤니티 페이지 참여한 인원 수 정보 제공

- app/src/main/java/com/sandamso/sansaninfo/signpage/FindpwActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/signpage/FindpwResultActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/signpage/SignInActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/signpage/SignUpActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/signpage/SignUpDialog.kt
> [REFACTOR]: 패키지명 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sandamso/sansaninfo/UserPopUp.kt
- app/src/main/java/com/sandamso/sansaninfo/addpage/AddPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChatRoomActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/communitypage/CommunityPageAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/data/PostModel.kt
- app/src/main/java/com/sandamso/sansaninfo/data/RoomData.kt
- app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
- app/src/main/res/drawable/btn_desert_borderless2.xml
- app/src/main/res/layout/activity_chatting_page.xml
- app/src/main/res/layout/activity_user_pop_up.xml
- app/src/main/res/layout/chatting_list_item.xml
- app/src/main/res/values/strings.xml
- 채팅룸에서 채팅방에 입장하여 대화 상대를 확인하는 기능 
- 채팅룸에서 D-Day 날짜 보여주는 기능
- 수정하기에서 날짜 변경해도 채팅룸 디데이도 변경되게 수정
- 수정하기 이미지 안고르면 수정안되는 오류 수정  
- 애드페이지 확인버튼, 변경버튼 색깔 변경(피드백) 
- 커뮤니티 페이지 참여한 인원 표시 추가 수정 
- 채팅방 나가는 경우 커뮤니티 페이지 인원 추가 수정 
- 커뮤니티 페이지 중복하여 참여하는 경우 추가 수정
- 채팅방 리스트에서 마지막 메세지 보여주는 기능
> [Feature] 채팅관련 기능 수정 및 추가

- app/src/main/java/com/sandamso/sansaninfo/communitypage/CommunityPageFragment.kt
- 인기순 정렬 기준 선택 시 참여순이 많은 게시글대로 올림차순 정렬
- CommuntyPageFragment 
close #185
> [Community-page] 인기순 정렬 기능 구현완료

- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChatRoomActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListAdapter.kt
- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
- app/src/main/java/com/sandamso/sansaninfo/signpage/SignInActivity.kt
- app/src/main/res/layout/activity_user_pop_up.xml
> [Feature, Fix] 채팅방 관련 오류 수정 및 기능 추가

- app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
- app/src/main/java/com/sandamso/sansaninfo/mypage/MyPageFragment.kt
> [FEAT] : ⚙️: 회원 탈퇴 기능 추가
